### ISSUE TITLE
German Teutonic Order conquest doesn't properly wipe out Holy City religion

### ISSUE THREAD

**Issue by Enrico-Swagolo** [adaneslavo/More-Unique-Components-for-VP#144]
version : current, unless some ninja-release came out

If you conquer a city after Teutonic Order, it'll properly turn opposing religion into atheists. The only problem is if it occurs to a Holy City, then everyone from other religions is converted to atheists, but the base religious +30 pressure that always affects holy cities remains, so you have to wait until 1 citizen turns before using an inquisitor if you really want the pressure off.

**Comment by adaneslavo** [comment]
So if I understood correctly you have only your religion + atheist in the city (catholic f.e.) , but muslim pressure (because it was muslim holy city) is still on. Then you need to wait until 1 person converts to muslim (from that pressure) to convert make use of inquisitor and totally wipe out muslim religion. Right?

I think we cannot do much about this. We use lua, and lua has ready function that changes peoples faith in the city. we do not affect pressury in any way. @infixo can you help us and tell if there's any way to make that happen? To wipe out foreign pressure in addition to followers?

**Comment by Enrico-Swagolo** [comment]
Yes, that is correct. For instance Catholic Germany takes the Islamic Holy
City Paris, every non-catholic is turned into an atheist but the holy city
pressure remains even if hovering over the city doesn't mention it being a
Holy City.

**Comment by pineappledan** [comment]
Sounds like it's working as intended, more or less

**Comment by Infixo** [comment]
1. Religious pressure from being a Holy City is added to the city regardless of existing religions, followers, etc. It's just from being a Holy City.
2. I see no Lua functions to deal with religious pressure. It seems that it is fully done inside DLL as an auto-process.

**Comment by Infixo** [comment]
Also, I don't see why somebody thinks that there's an error somewhere here. Chapter promo "un-converts" followers. And it does. It doesn't say "removes a religion". Should be closed, there's no error here.
