### ISSUE TITLE
Arabia's Madrasah Isn't Scaling With Era

### ISSUE THREAD

**Issue by grmagne** [adaneslavo/More-Unique-Components-for-VP#147]
I've bought a few units with Faith using Zealotry on Epic speed. Regardless of the era the Madrasah is only providing 30 science.  That accounts for the 150% Epic scaling but I never get the bonus according to the text for "Scales with Era".

**Comment by pineappledan** [comment]
I have increased the madrasah yields to 20/100, up from 10/50.  This is now consistent with what the text description says. 
The lua clearly has a era modifier, so if the speed scaler is working there is no reason why the era scaler would not be. It could be that the scaler was so small (due to the base 10), that it wasn't noticeable.
