### ISSUE TITLE
Proxenos not giving +2 gold to Capital

### ISSUE THREAD

**Issue by IllusVirus** [adaneslavo/More-Unique-Components-for-VP#152]
If I understood it correctly, Proxenos is supposed to give +2 gpt to Capital for completing diplo missions, which it does not seem to be doing. If it meant it adds +2 more gold to the 1 gold given by diplo missions, that does not seem to be working either.

*Love this mod mod btw, gave VP a breathe of fresh air*

**Comment by pineappledan** [comment]
What version of the modmod are you using? 

The Proxenos promotion was broken in previous versions (up to v31, I believe) but should be fixed in the most up-to-date version.

**Comment by IllusVirus** [comment]
I believe I am on the latest one, I do recall downloading 32.2, but when I 'install' it I noticed that it says its v32, unless the mini versions are never indicated. The changelog has no indication of the fix, but I suppose its not significant enough to be mentioned.

I'll attempt to re-install and see if that fixes it. Thank you.

**Comment by pineappledan** [comment]
The fix was made in mid April, so you definitely a version that is up to date.

I will try to replicate it on my end this weekend

**Comment by IllusVirus** [comment]
Okay. I'll try things again too on my end. Thanks again!

**Comment by Infixo** [comment]
Proxenos uses UnitPrekill event which needs to be enabled first by setting EVENTS_UNIT_PREKILL to 1.

**Comment by pineappledan** [comment]
grr....
That was in there before... Who removed it?

**Comment by pineappledan** [comment]
I still haven't gotten around to testing it :(

**Comment by adaneslavo** [comment]
Ouch! :]

**Comment by adaneslavo** [comment]
I will look into it then.

**Comment by adaneslavo** [comment]
It can see the unit, but is unable to see promotions on that unit. I had same problem with "Diplomatic Reciprocity" when I wanted to check if the unit is creating embassy or doing normal mission. I cannot because the unit had no coordinates or something. So i did it only to work as now.

I checked but there's no diplo events like "OnGreatPErsonExpensanded" I used in DR. Change?

**Comment by adaneslavo** [comment]
I made it work. The only thing hat concerns me is how to differentiete diplomatic mission from death on foreign territory? Code will not see the difference.

**Comment by pineappledan** [comment]
So right now it check if eCiv ~= -1, so it will trigger as long as the unit dies in non-neutral territory. 

Does this mean the only thing that was going wrong was the IsMinorCiv() check? 

What happens if we change that to "if eCiv >= 22"?

According to[ this section of the modiki,](http://modiki.civfanatics.com/index.php?title=PlayerID_(Civ5_Type)) civ number between 22 and 63 are reserved for city-states

**Comment by adaneslavo** [comment]
**I changed also promotion name. It was wrong.**
I deleted minor civ because on main page there was no info that it should work only for CSs. I made it work for all civs.
I think this function trigger when unit dies or is expended. Then it is treated as "dead". I suppose. It needs to be checked,

**Comment by adaneslavo** [comment]
So the check is unnecessary if diplo units can be used only on cs.

**Comment by pineappledan** [comment]
Without the check, it is possible to trigger the +2g in the capital by having your diplo unit get captured or deleted in another civ's territory.

Technically, this check wouldn't prevent the trigger if the unit were captured/deleted in a CS's territory, but we would assume that if a diplo unit is inside a CS territory, it is going to expend itself with a diplo mission. 

Overall, I'm fairly unconcerned with the issue. The chances that people are going to delete a unit like this, or get it caught on purpose is remote, since they would be missing out on 35 influence, but if it can be easilly done, and the minor civ check doesn't cause any issues, then it may as well stay

**Comment by adaneslavo** [comment]
Ok.

**Comment by adaneslavo** [comment]
Change description on main site. Also Barbican had some tab issue after your last update :P
