### ISSUE TITLE
Penteconter?

### ISSUE THREAD

**Issue by Infixo** [adaneslavo/More-Unique-Components-for-VP#96]
Why do I have in my game? What is that?

**Comment by pineappledan** [comment]
It is the exact same as the dromon in normal VP, just an art change. the Dromon is now a unique penteconter replacement for Byzantium

**Comment by Infixo** [comment]
Why is Penteconter not a unique? Dromon is a common VP unit. You are adding new units, why change existing ones?

**Comment by pineappledan** [comment]
a few reasons: 
- because the idea of a ranged naval unit isn't all that special, but the idea of a 1st century napalm flamethrower on a boat is pretty special
- Because VP co-opted a unique unit from byzantium to make it a base unit; what we did was restore it back to its orignal place
- because, while triremes are maybe too specific for comfort, w.r.t. how they were used in civ to signify any and all early warships from any culture, using dromons and greek fire to represent the universal concept of ranged naval combat is beyond the pail
